<?php 
	        $cm='active';
	        $lsr='active';

        include_once('including/all-include.php');
        include_once('including/header.php');
			unset($_SESSION['working-active-asset']);
			
			
			//print_r($_SESSION);
        ?>
  
  
  <script type="text/javascript">
function PrintPage()
{
 window.print();
}
</script>

<style>
@media print
{
    
    .no-print
    {
        display: none !important;
        height: 0;
    }


    .no-print, .no-print *{
        display: none !important;
        height: 0;
    }
}
</style>

          

				<!-- BEGIN PAGE CONTENT-->
				<div class="row-fluid">
					<div class="span12">
						<!-- BEGIN EXAMPLE TABLE PORTLET-->
						<div class="portlet box blue">
							<div class="portlet-title">
								<h4><i class="icon-edit"></i>List of All Depedency Lead</h4>
								<div class="tools">
									<a href="javascript:;" class="collapse"></a>
									<a href="#portlet-config" data-toggle="modal" class="config"></a>
									<a href="javascript:;" class="reload"></a>
									<a href="javascript:;" class="remove"></a>
								</div>
							</div>
							<div class="portlet-body">
								<div class="clearfix">
                                	<div class="btn-group">
										<!-- button display area !-->
									</div>
                                    	
                                        
                   <div class="btn-group pull-right">
										<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
										</button>
										<ul class="dropdown-menu">
											<li><a href="#" onClick="PrintPage()">Print</a></li>

											<li><a href="#">Export to Excel</a></li>
										</ul>
									</div>
								</div>
								<table class="table table-striped table-hover table-bordered" id="sample_1">
									<thead>
										<tr>
											<!--<th>Lead ID</th>-->
                                            <th>#</th>
                                            <th>Lead ID</th>
                                            <th width="15%">Account Name</th>
											<!--<th >CKA Type</th>-->
										<!--	<th >Project Type</th>-->
											<th width="15%">Project Name</th>
											<!--<th >State</th>-->
											<th>City</th>
											<!--<th >Architect Name</th>-->
                                          <!--  <th>Tile Stage Date</th>-->
                                            <th>OBL Forecast (INR Lac)</th>
                                            <th>Request For</th>
                                            <th>Request Activity</th>
                                            <th>Request By</th>
                                            <!--<th>Status</th>-->
<!--                                            <th>Win %</th>
                                            <th>Tiling Date</th>
                                            <th>Generated By</th>
-->                                         <!--   <th>Status</th>-->
                                            <th>Sales Phase</th>
                                            <th width="10%">Action</th>
                                        </tr>
									</thead>
									<tbody>
									
       <?php
	
	$sql="SELECT 
	cart.opportunity_id,
	d.lead_id,
	cart.action_status,
	cart.responsible_owner,
	cart.added_by,
	cart.activity,
	cart.last_modified,
	d.opportunity_id,
	 a.cka_name,
	 b.cka_type,
	 c.project_type,
	 d.[project_name],
	 e.state_name,
	 d.[city],
	 d.[architect_name],
	 d.[tile_stage_date],
	 d.[obl_sale_forecast_inr],
	 d.[probability_of_win],
	 d.[status],
	 d.deal_type,
	 d.territory,
	 d.current_stage,
	 u.fullname
  FROM project_action_plan_cart cart
  left join [opportunity] d on cart.opportunity_id = d.opportunity_id
  left join cka_name_master a on a.cka_name_id = d.cka_name_id
  left join cka_type_master b on b.cka_type_id = d.cka_type_id
  left join project_type_master c on c.project_type_id = d.project_type_id
  left join state_master e on e.state_id = d.state_id 
  left join user_management u on d.created_by = u.uid
  ";
  
    if(trim($_SESSION['user_type'])=='management') {
		$sql.="  where 1=1  ";
	}else{
		$sql.="  where 1=1 and ( ";		
				
					if(empty($_SESSION['my_team_id'])){
						$ttid=$_SESSION['uid'];
					}else{
						if($_SESSION['user_type']=='manager'){
							$ttid=$_SESSION['my_team_id'].','.$_SESSION['uid'];
						}else{
							$ttid=$_SESSION['my_team_id'];
						}
					}
					
					$exx=explode(",",$ttid);
							$xxcnt=0;
						foreach ($exx as $vxx){
						//echo $vx;
							if($xxcnt==0)
								$sql .=" cart.responsible_owner = '".$vxx."' ";
							else
								$sql .=" or cart.responsible_owner = '".$vxx."' ";
							$xxcnt++;
						}
						$sql .=" ) ";
		}
					
									$sql .=" and cart.action_status='0' or cart.action_status='1' order by last_modified desc ";
									//echo $sql;
									$rs=odbc_exec($conn,$sql);
									$count=1;
									while($f = odbc_fetch_array($rs)){
										
										//print_r($f);
										echo '<tr>';
										echo '<td>'.$count++.'</td>';
										echo '<td>'.$f['lead_id'].'</td>';
										echo '<td>'.$f['cka_name'].'</td>';
										//echo '<td>'.$f['cka_type'].'</td>';										
										//echo '<td >'.$f['project_type'].'</td>';																
										echo '<td>'.ucfirst($f['project_name']).'</td>';	
										//echo '<td>'.ucfirst(strtolower($f['state_name'])).'</td>';	
										echo '<td>'.$f['city'].'</td>';
										//echo '<td>'.$f['architect_name'].'</td>';
										//echo '<td>'.$f['tile_stage_date'].'</td>';
										
										//echo '<td>'.valchar(trim($f['obl_sale_forecast_inr'])).'</td>';
										echo '<td>'.number_format(trim($f['obl_sale_forecast_inr']/100000),0).'</td>';

										//echo '<td>'.number_format(trim($f['obl_sale_forecast_inr']),0).'</td>';
										//echo '<td align="center">'.ucfirst($f['probability_of_win']).'</td>';
										//echo '<td>'.date('d-m-Y',strtotime(trim($f['tile_stage_date']))).'</td>';
										//echo '<td>'.$f['fullname'].'</td>';

										$eq="select fullname from user_management where uid='".$f['responsible_owner']."' ";
										$eqe=odbc_exec($conn,$eq);
										$eqf=odbc_fetch_array($eqe);
										echo '<td>'.$eqf['fullname'].'</td>';

										echo '<td>'.$f['activity'].'</td>';
										
										$eq1="select fullname from user_management where uid='".$f['added_by']."' ";
										$eqe1=odbc_exec($conn,$eq1);
										$eqf1=odbc_fetch_array($eqe1);
										echo '<td>'.$eqf1['fullname'].'</td>';
	
										
										if(trim($f['current_stage'])=='1'){
											$cstage='Opportunity';
										}
										
										if(trim($f['current_stage'])=='2'){
											$cstage='Discussion';
										}
										
										if(trim($f['current_stage'])=='3'){
											$cstage='Sampling';
										}
										
										if(trim($f['current_stage'])=='4'){
											$cstage='Product Approval';
										}
										
										if(trim($f['current_stage'])=='5'){
											$cstage='Quotation';
										}
										
										if(trim($f['current_stage'])=='6'){
											$cstage='Negotiation';
										}
										
										if(trim($f['current_stage'])=='7'){
											$cstage='Won';
										}
										
										if(trim($f['status'])=='open'){
											//echo '<td align="center"><span class="label label-warning">Open</span></td>';
											echo '<td>'.$cstage.'</td>';
			echo '<td >';
				echo '<a href="action-plan-feedback-update.php?pid='.$f['opportunity_id'].'" class="btn mini blue no-print"><i class="icon-edit"></i> Update</a>';
				echo '<a href="lead-history.php?pid='.$f['opportunity_id'].'" class="btn mini yellow no-print"><font color="#000">Detail&nbsp;</font></a>';
				
			echo '</td>';
										}
																		
									
										if(trim($f['status'])=='close'){
											//echo '<td align="center"><span class="label label-success">Won</span></td>';
											echo '<td>'.$cstage.'</td>';
			echo '<td >';
				echo '<a href="action-plan-feedback-update.php?pid='.$f['opportunity_id'].'" class="btn mini blue no-print"><i class="icon-edit"></i> Update</a>';
				echo '<a href="lead-history.php?pid='.$f['opportunity_id'].'" class="btn mini yellow no-print"><font color="#000">Detail&nbsp;</font></a>';
				
			echo '</td>';
										}
										
										
										if(trim($f['status'])=='lost'){
											//echo '<td align="center"><span class="label label-important">Lost</span></td>';
											echo '<td>'.$cstage.'</td>';
			echo '<td >';
				//echo '<a href="add-opportunity.php?pid='.$f['opportunity_id'].'" class="btn mini blue no-print"><i class="icon-edit"></i> Update</a>';
				echo '-';
			echo '</td>';
										}
						//echo '<a href="asset-master.php?delid='.$f['asset_id'].'" class="btn mini red"><i class="icon-trash"></i> Delete</a>';
						//echo '&nbsp;';		

	
									}
									?>
       
									</tbody>
								</table>
							</div>
						</div>
						<!-- END EXAMPLE TABLE PORTLET-->
					</div>
				</div>
				<!-- END PAGE CONTENT -->
			</div>
			<!-- END PAGE CONTAINER-->
		</div>
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->
  <!-- END CONTAINER -->
   <?php include_once('including/footer.php')?>
      <?php 

   if(isset($_GET['msgTxt']) && isset($_GET['msgType'])){
			$ms=base64_decode($_GET['msgTxt']);
                echo '<script>alert(\''.$ms.'\');</script>';
            }
   ?>