<?php 
	        $pm='active';
	        $app='active';

        include_once('including/all-include.php');
        include_once('including/header.php');
			unset($_SESSION['working-active-asset']);
			
			
			//print_r($_SESSION);
        ?>
  
  
  <script type="text/javascript">
function PrintPage()
{
 window.print();
}
</script>

<style>
@media print
{
    
    .no-print
    {
        display: none !important;
        height: 0;
    }


    .no-print, .no-print *{
        display: none !important;
        height: 0;
    }
}
</style>

          

				<!-- BEGIN PAGE CONTENT-->
				<div class="row-fluid">
					<div class="span12">
						<!-- BEGIN EXAMPLE TABLE PORTLET-->
						<div class="portlet box blue">
							<div class="portlet-title">
								<h4><i class="icon-edit"></i>List of Pending Approvals</h4>
								<div class="tools">
									<a href="javascript:;" class="collapse"></a>
									<a href="#portlet-config" data-toggle="modal" class="config"></a>
									<a href="javascript:;" class="reload"></a>
									<a href="javascript:;" class="remove"></a>
								</div>
							</div>
							<div class="portlet-body">
								<div class="clearfix">
                                	<div class="btn-group">
										<!-- button display area !-->
									</div>
                                    	
                                        
                   <div class="btn-group pull-right">
										<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
										</button>
										<ul class="dropdown-menu">
											<li><a href="#" onClick="PrintPage()">Print</a></li>

											<li><a href="#">Export to Excel</a></li>
										</ul>
									</div>
								</div>
								<table class="table table-striped table-hover table-bordered" id="sample_1">
									<thead>
										<tr>
											<!--<th>Lead ID</th>-->
                                            <th>#</th>
                                            <th width="15%">Leads ID</th>
											<!--<th >CKA Type</th>-->
										<!--	<th >Project Type</th>-->
											<th width="15%">Account Name</th>
											<th width="15%">Project Name</th>
											<!--<th >State</th>-->
											<th>City</th>
											<!--<th >Architect Name</th>-->
                                          <!--  <th>Tile Stage Date</th>-->
                                            <th>OBL Forecast (INR Lac)</th>
                                            <th>Submitted By</th>
                                            <th>Tile Stage Date</th>
                                            
                                            <!--<th>Status</th>-->
<!--                                            <th>Win %</th>
                                            <th>Tiling Date</th>
                                            <th>Generated By</th>
-->                                         <!--   <th>Status</th>-->
                                            <th>Sales Phase</th>
                                            <th width="10%">Action</th>
                                        </tr>
									</thead>
									<tbody>
									
       <?php
	
		$sql="SELECT distinct
o.opportunity_id, 
o.lead_id,
c.cka_name,
o.project_name,
o.city,
o.obl_sale_forecast_inr,
u.fullname,
o.tile_stage_date,
p.stage_name



from opportunity o 
inner join fld f on f.opp_id = o.opportunity_id
inner join cka_name_master c on c.cka_name_id = o.cka_name_id
inner join user_management u on u.uid = o.created_by
inner join pmt_current_stage p on p.stage_id = o.current_stage

";
  
    if(trim($_SESSION['user_type'])=='management') {
		$sql.="  where 1=1  ";
									$sql.=" and f.status = 1";
									$rs=odbc_exec($conn,$sql);
									$count=1;
									while($f = odbc_fetch_array($rs)){
										$cstage = $f['stage_name'];
										
										//print_r($f);
										echo '<tr>';
										echo '<td>'.$count++.'</td>';
										//echo '<td>'.$f['opportunity_id'].'</td>';
										echo '<td>'.$f['lead_id'].'</td>';
										//echo '<td>'.$f['cka_type'].'</td>';										
										echo '<td >'.$f['cka_name'].'</td>';																
										echo '<td>'.ucfirst($f['project_name']).'</td>';	
										//echo '<td>'.ucfirst(strtolower($f['state_name'])).'</td>';	
										echo '<td>'.$f['city'].'</td>';
										//echo '<td>'.$f['architect_name'].'</td>';
										//echo '<td>'.$f['tile_stage_date'].'</td>';
										
										//echo '<td>'.valchar(trim($f['obl_sale_forecast_inr'])).'</td>';
										echo '<td>'.number_format(trim($f['obl_sale_forecast_inr']/100000),0).'</td>';

									
										echo '<td >'.$f['fullname'].'</td>';
										echo '<td >'.date('d-m-Y',strtotime(trim($f['tile_stage_date']))).'</td>';
										echo '<td >'.$cstage.'</td>';
			echo '<td >';
				echo '<a href="approval_request_update.php?pid='.$f['opportunity_id'].'" class="btn mini blue no-print"><i class="icon-edit"></i> Update</a>';
				echo '<a href="lead-history.php?pid='.$f['opportunity_id'].'" class="btn mini yellow no-print"><font color="#000">Detail&nbsp;</font></a>';
				
			echo '</td>';
										}
																		
									
										
										
										
										
						//echo '<a href="asset-master.php?delid='.$f['asset_id'].'" class="btn mini red"><i class="icon-trash"></i> Delete</a>';
						//echo '&nbsp;';		

}
									
									?>
       
									</tbody>
								</table>
							</div>
						</div>
						<!-- END EXAMPLE TABLE PORTLET-->
					</div>
				</div>
				<!-- END PAGE CONTENT -->
			</div>
			<!-- END PAGE CONTAINER-->
		</div>
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->
  <!-- END CONTAINER -->
   <?php include_once('including/footer.php')?>
      <?php 

   if(isset($_GET['msgTxt']) && isset($_GET['msgType'])){
			$ms=base64_decode($_GET['msgTxt']);
                echo '<script>alert(\''.$ms.'\');</script>';
            }
   ?>